FROM nvidia/cuda:12.1.1-devel-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y python3 python3-pip git nodejs npm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip
RUN pip install -Uq jupyterlab ipywidgets
RUN pip install -q optimum["onnxruntime"]

ARG USER
RUN useradd -ms /bin/bash ${USER}
USER ${USER}
WORKDIR /home/${USER}/
ENV PATH="/home/${USER}/.local/bin:${PATH}"

