FROM nvidia/cuda:11.8.0-devel-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install --upgrade pip

RUN apt-get install -y git nodejs npm
RUN pip install -Uq jupyterlab ipywidgets

ARG USER
RUN useradd -ms /bin/bash ${USER}
USER ${USER}
WORKDIR /home/${USER}/
ENV PATH="/home/${USER}/.local/bin:${PATH}"

RUN pip install tensorflow[and-cuda]
